### ISSUE TITLE
Not working on Android lollipop with sdk 21

### ISSUE THREAD

**Issue by shingz96** [wubydax/6thGear-RomControl-v2.0#1]
Some prefs will result in error inflating such as open app, uri selection and color picker

**Comment by wubydax** [comment]
We have adressed this issue originally on xda but let's close it once and for all:
1. The code as is runs on all the emulators starting sdk 21 (android 5.0 and up). No issues known
2. There is a disclaimer on top of each file which claims:

> This program is distributed in the hope that it will be useful,
>         but WITHOUT ANY WARRANTY; without even the implied warranty of
>         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>         GNU General Public License for more details.

Therefore, this code is given to you free of any obligation from our side to fix any issues. If you experience an issue with particular device, as developer it is your obligation to fix the forked code to work on said device. As you're under NO obligation to use this code. We repeat, code as is runs on any tested android emulator with sdk 21 and up. This is an open source project. You should be an android developer to use and mainain it if you choose to use it. 

Issue closed for lack of validity under given license.
